steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  args:
  - '-c'  
  - |
    echo "Uploading updated files to Cloud Storage without deleting existing files..."
    gsutil -m rsync -r . gs://muqaddasfiaz.site
    echo "Invalidating Cloud CDN cache..."
    gcloud compute url-maps invalidate-cdn-cache  medi-lb --path "/*"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'
